"""initial tables

Revision ID: e8805db11b64
Revises: 
Create Date: 2025-06-16 17:29:53.423498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8805db11b64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_metrics_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencer_metrics_history_id'), 'influencer_metrics_history', ['id'], unique=False)
    op.create_index('ix_user_id_recorded_at', 'influencer_metrics_history', ['user_id', 'recorded_at'], unique=False)
    op.create_table('post_metrics_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_code', sa.String(length=50), nullable=False),
    sa.Column('post_id', sa.String(length=50), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_code_recorded_at', 'post_metrics_history', ['post_code', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_post_metrics_history_id'), 'post_metrics_history', ['id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.Enum('influencer', 'post', name='tasktypeenum'), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('post_code', sa.String(length=255), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'stopped', name='taskstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_code'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_status', 'task', ['status'], unique=False)
    op.create_index('ix_task_type', 'task', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_type', table_name='task')
    op.drop_index('ix_status', table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_post_metrics_history_id'), table_name='post_metrics_history')
    op.drop_index('ix_post_code_recorded_at', table_name='post_metrics_history')
    op.drop_table('post_metrics_history')
    op.drop_index('ix_user_id_recorded_at', table_name='influencer_metrics_history')
    op.drop_index(op.f('ix_influencer_metrics_history_id'), table_name='influencer_metrics_history')
    op.drop_table('influencer_metrics_history')
    # ### end Alembic commands ###
